/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PortfolioData } from '../types';

/**
 * =========================================================================
 * CENTRAL PORTFOLIO DATA CONFIGURATION
 * =========================================================================
 * This is the master default dataset for Tofayel Ahmad Shible's portfolio.
 * The website reads this data and supports full real-time live editing,
 * persistence to localStorage, custom image uploading, and JSON backup/restore.
 */

export const DEFAULT_PORTFOLIO_DATA: PortfolioData = {
  personal: {
    name: "Tofayel Ahmad Shible",
    shortName: "Tofayel A. Shible",
    title: "Graphic Designer & Video Editor",
    shortBio: "Dedicated Graphic Designer and Video Editor crafting modern graphics, engaging videos, and AI-powered creative solutions.",
    bio: "I am Tofayel Ahmad Shible, a dedicated and motivated Graphic Designer and Video Editor based in Jurain, Shyampur, Dhaka. Eager to apply my technical and professional skills in graphic design, video editing, and digital media, work collaboratively, and contribute effectively to achieving organization goals.",
    location: "Jurain, Shyampur, Dhaka-1204, Bangladesh",
    shortLocation: "Jurain, Shyampur, Dhaka-1204",
    trainingSummary: "Certified from As-Sunnah Skill Development Institute in Small Business Management (Batch 37, 2026), specializing in Graphic Design, Video Editing & AI Tools.",
    // Curated high quality creative portraits and graphics
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    heroBannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
    availabilityStatus: "available",
    availabilityText: "Available for freelance & full-time projects",
    yearsExperience: "3 Months+",
    completedProjectsCount: "150+",
    happyClientsCount: "60+",
    satisfactionRate: "99%",
  },

  contact: {
    email: "tofaylsible52@gmail.com",
    phone: "01798825795",
    whatsapp: "+8801798825795",
    whatsappDirectUrl: "https://wa.me/8801798825795",
    location: "Jurain, Shyampur, Dhaka-1204, Bangladesh",
    addressDetail: "Jurain, Shyampur, Dhaka-1204",
    workingHours: "Saturday – Thursday (9:00 AM – 10:00 PM BST)",
  },

  socialLinks: [
    {
      id: "social-email",
      platform: "email",
      label: "Email",
      url: "mailto:tofaylsible52@gmail.com",
      iconName: "Mail",
    },
    {
      id: "social-phone",
      platform: "phone",
      label: "Phone",
      url: "tel:01798825795",
      iconName: "Phone",
    },
    {
      id: "social-whatsapp",
      platform: "whatsapp",
      label: "WhatsApp",
      url: "https://wa.me/8801798825795",
      iconName: "WhatsApp",
    },
    {
      id: "social-facebook",
      platform: "facebook",
      label: "Facebook Profile",
      url: "https://www.facebook.com/tofaylahmad.sible",
      iconName: "Facebook",
    },
    {
      id: "social-facebook-page",
      platform: "facebook",
      label: "Facebook Page",
      url: "https://www.facebook.com/share/1dfSUnWCuk/",
      iconName: "Facebook",
    },
    {
      id: "social-behance",
      platform: "behance",
      label: "Behance Portfolio",
      url: "https://behance.net/tofayelshible",
      iconName: "Behance",
    },
    {
      id: "social-youtube",
      platform: "youtube",
      label: "YouTube Works",
      url: "https://youtube.com",
      iconName: "Youtube",
    },
    {
      id: "social-linkedin",
      platform: "linkedin",
      label: "LinkedIn",
      url: "https://linkedin.com/in/tofayel-shible",
      iconName: "Linkedin",
    },
  ],

  demoReel: {
    title: "Featured Video Editing & Creative Showreel",
    subtitle: "A showcase of dynamic pacing, precision color grading, motion graphics, and narrative editing.",
    videoType: "youtube",
    videoUrl: "https://www.youtube.com/watch?v=YLCEuvafChw",
    thumbnailUrl: "https://img.youtube.com/vi/YLCEuvafChw/hqdefault.jpg",
    role: "Lead Video Editor & Motion Designer",
    softwareUsed: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "CapCut"],
    description: "Featured highlight reel capturing fast-paced YouTube storytelling, short-form viral transitions, podcast audio mastering, cinematic color grades, and branded social marketing spots.",
    highlights: [
      "Dynamic sound design & audio clean-up",
      "Custom motion graphics & title sequences",
      "Pacing tailored for viral engagement and retention",
      "Cinema-grade multi-camera color matching",
    ],
  },

  projects: [
    {
      id: "proj-1",
      title: "E-Commerce Brand Social Media Campaign",
      category: "Graphic Design",
      subCategory: "Social Media Post Design",
      thumbnailUrl: "https://images.unsplash.com/photo-1542744094-3a31727221eb?auto=format&fit=crop&w=900&q=80",
      description: "Cohesive Instagram carousel ads, promotional banner packages, and seasonal discount visual identities for an apparel brand.",
      clientName: "Aura Apparel (Demo Client)",
      softwareUsed: ["Photoshop", "Illustrator", "Figma"],
      featured: true,
      projectDate: "2025",
      demoUrl: "",
      aspectRatio: "1:1",
    },
    {
      id: "proj-2",
      title: "Modern Minimalist Brand Identity & Logo Suite",
      category: "Graphic Design",
      subCategory: "Logo & Stationery Design",
      thumbnailUrl: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=900&q=80",
      description: "Vector logo marks, business card layouts, corporate stationery guidelines, and high-resolution print-ready mockups.",
      clientName: "Apex Innovations (Demo Client)",
      softwareUsed: ["Illustrator", "Photoshop", "Figma"],
      featured: true,
      projectDate: "2025",
      demoUrl: "",
      aspectRatio: "4:5",
    },
    {
      id: "proj-3",
      title: "High-CTR YouTube Thumbnail & Cover Design",
      category: "Graphic Design",
      subCategory: "YouTube Thumbnail Design",
      thumbnailUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80",
      description: "Eye-catching thumbnails optimized for click-through rate with high-contrast character cutouts, expressive expressions, 3D text glow, and storytelling.",
      clientName: "Global Gaming & Vloggers (Demo Client)",
      softwareUsed: ["Photoshop", "Illustrator", "Canva"],
      featured: true,
      projectDate: "2025",
      demoUrl: "",
      aspectRatio: "16:9",
    },
    {
      id: "proj-3b",
      title: "Creative Banner & Print Promotion Kit",
      category: "Graphic Design",
      subCategory: "Banner & Poster Design",
      thumbnailUrl: "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?auto=format&fit=crop&w=900&q=80",
      description: "High-resolution roll-up banners, event posters, billboard prints, and digital ads with crisp typography and vibrant visual hierarchy.",
      clientName: "Digital Horizon (Demo Client)",
      softwareUsed: ["Photoshop", "Illustrator"],
      featured: true,
      projectDate: "2025",
      demoUrl: "",
      aspectRatio: "16:9",
    },
    {
      id: "proj-4",
      title: "Featured Video Editing & Visual Storytelling",
      category: "Video Editing",
      subCategory: "YouTube Video Editing",
      thumbnailUrl: "https://img.youtube.com/vi/L6hsr78adkU/hqdefault.jpg",
      videoUrl: "https://youtu.be/L6hsr78adkU?si=CoBD3oPig4FY5nGo",
      description: "Engaging video edit with animated B-roll popups, smooth pacing, seamless sound design, and custom graphic transitions designed for high viewer retention.",
      clientName: "Tofayel Ahmad Shible",
      softwareUsed: ["Premiere Pro", "After Effects", "Photoshop", "CapCut"],
      featured: true,
      projectDate: "2025",
      demoUrl: "https://youtu.be/L6hsr78adkU?si=CoBD3oPig4FY5nGo",
      aspectRatio: "16:9",
    },
    {
      id: "proj-5",
      title: "Viral TikTok & Reels Short-Form Motion Cuts",
      category: "Video Editing",
      subCategory: "Reel/Short-form Editing",
      thumbnailUrl: "https://img.youtube.com/vi/SxHwddvPTDY/hqdefault.jpg",
      videoUrl: "https://youtu.be/SxHwddvPTDY?si=uRAjTk0en8AZzDBF",
      description: "High-hook 9:16 vertical short-form reels with dynamic kinetic typography, animated emojis, sound effects, and retention-focused framing.",
      clientName: "Tofayel Ahmad Shible",
      softwareUsed: ["CapCut", "Premiere Pro", "After Effects"],
      featured: true,
      projectDate: "2025",
      demoUrl: "https://youtu.be/SxHwddvPTDY?si=uRAjTk0en8AZzDBF",
      aspectRatio: "9:16",
    },
    {
      id: "proj-6",
      title: "Talking-Head & Podcast Video Editing",
      category: "Video Editing",
      subCategory: "Talking-head Video Editing",
      thumbnailUrl: "https://img.youtube.com/vi/uEm6Yzld8hA/hqdefault.jpg",
      videoUrl: "https://youtu.be/uEm6Yzld8hA?si=WcjY0OoRtYt1s0xU",
      description: "Multi-angle camera switching, AI-assisted noise reduction, clear captioning, chapter markers, and branded lower-thirds.",
      clientName: "Tofayel Ahmad Shible",
      softwareUsed: ["DaVinci Resolve", "Premiere Pro", "CapCut"],
      featured: true,
      projectDate: "2025",
      demoUrl: "https://youtu.be/uEm6Yzld8hA?si=WcjY0OoRtYt1s0xU",
      aspectRatio: "16:9",
    },
    {
      id: "proj-6b",
      title: "Cinematic Demo Reel & Promotional Cut",
      category: "Video Editing",
      subCategory: "Commercial & Promo Editing",
      thumbnailUrl: "https://img.youtube.com/vi/YLCEuvafChw/hqdefault.jpg",
      videoUrl: "https://www.youtube.com/watch?v=YLCEuvafChw",
      description: "High-energy commercial cut with rhythmic beat-sync transitions, sound design impacts, color grading, and motion graphics.",
      clientName: "Tofayel Ahmad Shible",
      softwareUsed: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
      featured: true,
      projectDate: "2025",
      demoUrl: "https://www.youtube.com/watch?v=YLCEuvafChw",
      aspectRatio: "16:9",
    },
  ],

  videoServices: [
    {
      id: "v-srv-1",
      title: "YouTube Video Editing",
      description: "End-to-end editing with story pacing, B-roll integration, custom sound design, and retention-focused edits.",
      iconName: "Youtube",
      deliverables: ["Full 1080p/4K Render", "Sound FX & Background Music", "Motion Graphics & Call-to-Actions"],
      badge: "Most Popular",
    },
    {
      id: "v-srv-2",
      title: "Reel / Short-Form Editing",
      description: "High-impact vertical videos for TikTok, Instagram Reels, and YouTube Shorts with trending pacing and kinetic text.",
      iconName: "Smartphone",
      deliverables: ["9:16 Vertical Video", "Auto/Custom Subtitles", "Viral Hook Transitions"],
      badge: "High Growth",
    },
    {
      id: "v-srv-3",
      title: "Talking-Head Video Editing",
      description: "Clean cuts for educators, coaches, and corporate speakers with multi-cam switching and crisp audio leveling.",
      iconName: "Mic",
      deliverables: ["Jump-cut Cleanup", "Presentation Slides Overlay", "Lower-Third Titles"],
    },
    {
      id: "v-srv-4",
      title: "Promotional Video Editing",
      description: "Commercials, product promo videos, and teaser ads that drive conversions for businesses and digital services.",
      iconName: "Megaphone",
      deliverables: ["Product Highlights", "Call-To-Action Animations", "Dynamic Music Sync"],
    },
    {
      id: "v-srv-5",
      title: "Subtitle & Caption Adding",
      description: "Accurate, stylized, animated captions with custom brand typography, emojis, and highlighting styles.",
      iconName: "Subtitles",
      deliverables: ["SRT & Hardcoded Subtitles", "Multi-Language Support", "Karaoke/Highlighted Words"],
    },
    {
      id: "v-srv-6",
      title: "Color Correction & Grading",
      description: "Transform flat LOG footage into cinematic, vibrant, filmic color spaces with accurate skin-tone preservation.",
      iconName: "SunMedium",
      deliverables: ["LUT Application", "White Balance Balancing", "Cinematic Mood Styling"],
    },
    {
      id: "v-srv-7",
      title: "Sound Cleanup & Audio Mastering",
      description: "Removal of background hiss, echo, and plosives; vocal EQ boosting; and spatial sound FX arrangement.",
      iconName: "Volume2",
      deliverables: ["Noise Reduction", "Voice Clarification", "Sound Effects Mixing"],
    },
    {
      id: "v-srv-8",
      title: "Motion Graphics & Title Animations",
      description: "Custom animated logos, subscribe buttons, lower thirds, progress bars, and infographic charts.",
      iconName: "Layers",
      deliverables: ["Alpha Channel Overlays", "Smooth Keyframe Motion", "Custom Template Packs"],
    },
  ],

  graphicServices: [
    {
      id: "g-srv-1",
      title: "YouTube Thumbnail Design",
      description: "Click-worthy, high-contrast visual thumbnails engineered to boost impressions and maximize CTR.",
      iconName: "Sparkles",
      deliverables: ["High-Res JPEG/PNG", "Click-Through Optimization", "Source PSD Included"],
      badge: "Best Value",
    },
    {
      id: "g-srv-2",
      title: "Social Media Post Design",
      description: "Visually cohesive feed posts, carousels, stories, and pins tailored for Instagram, Facebook, and LinkedIn.",
      iconName: "Share2",
      deliverables: ["Square & Portrait Formats", "Branded Templates", "Carousel Storyboards"],
    },
    {
      id: "g-srv-3",
      title: "Banner & Header Design",
      description: "Polished web banners, YouTube channel arts, LinkedIn banners, and Facebook page covers.",
      iconName: "Image",
      deliverables: ["Device-Responsive Safe Zones", "Crisp Typography", "Export for All Platforms"],
    },
    {
      id: "g-srv-4",
      title: "Poster & Flyer Design",
      description: "Striking event posters, conference brochures, corporate leaflets, and digital promotional flyers.",
      iconName: "FileText",
      deliverables: ["CMYK Print-Ready Files", "Digital Web Versions", "Bleed & Crop Marks"],
    },
    {
      id: "g-srv-5",
      title: "Logo & Brand Identity Design",
      description: "Timeless, versatile logos and mini brand identity packages that give your business a modern aesthetic.",
      iconName: "Compass",
      deliverables: ["Vector Formats (AI/SVG/EPS)", "Monochrome & Color Variations", "Brand Style Board"],
    },
    {
      id: "g-srv-6",
      title: "Business Card & Visiting Card",
      description: "Premium double-sided digital & print visiting cards with modern minimalism, QR integration, and clean typography.",
      iconName: "CreditCard",
      deliverables: ["Print Ready 300 DPI", "QR Code Generation", "Editable Master Files"],
    },
    {
      id: "g-srv-7",
      title: "Product Advertisement Creatives",
      description: "Eye-catching commercial product ads for Meta Ads, Google Display, and e-commerce hero banners.",
      iconName: "ShoppingBag",
      deliverables: ["E-Commerce Mockups", "Ad Creative Sets", "A/B Testing Variants"],
    },
    {
      id: "g-srv-8",
      title: "T-Shirt & Apparel Design",
      description: "Custom typography, vector illustrations, trendy streetwear prints, and apparel graphics ready for screen print or DTG.",
      iconName: "Shirt",
      deliverables: ["Vector Print Files (AI/EPS/SVG)", "300 DPI Transparent PNG", "Realistic Fabric Mockups"],
      badge: "Trending",
    },
  ],

  softwareSkills: [
    {
      id: "sw-1",
      name: "Adobe Photoshop",
      category: "Design",
      iconName: "Image",
      proficiency: 96,
      glowColor: "blue",
      description: "Photo manipulation, social media creatives, high-CTR YouTube thumbnails, and raster graphics.",
      accentHex: "#31A8FF",
    },
    {
      id: "sw-2",
      name: "Adobe Illustrator",
      category: "Design",
      iconName: "PenTool",
      proficiency: 93,
      glowColor: "orange",
      description: "Vector logos, brand identity, typography, vector illustrations, and print-ready designs.",
      accentHex: "#FF9A00",
    },
    {
      id: "sw-3",
      name: "Canva Pro",
      category: "Design",
      iconName: "Sparkles",
      proficiency: 95,
      glowColor: "cyan",
      description: "Quick social media creatives, presentation decks, templates, and rapid branding assets.",
      accentHex: "#00C4CC",
    },
    {
      id: "sw-4",
      name: "Adobe Premiere Pro",
      category: "Video",
      iconName: "Video",
      proficiency: 96,
      glowColor: "purple",
      description: "Timeline multi-cam video editing, narrative pacing, audio synchronization, and color grading.",
      accentHex: "#9999FF",
    },
    {
      id: "sw-5",
      name: "Adobe After Effects",
      category: "Motion",
      iconName: "Layers",
      proficiency: 90,
      glowColor: "purple",
      description: "Motion graphics, kinetic typography, visual effects, lower-thirds, and logo animations.",
      accentHex: "#9999FF",
    },
    {
      id: "sw-6",
      name: "CapCut",
      category: "Video",
      iconName: "Film",
      proficiency: 98,
      glowColor: "pink",
      description: "Viral short-form Reels, TikToks & Shorts, dynamic subtitles, sound effects, and speed ramps.",
      accentHex: "#FF4081",
    },
    {
      id: "sw-7",
      name: "InShot",
      category: "Video",
      iconName: "Smartphone",
      proficiency: 93,
      glowColor: "pink",
      description: "Fast mobile video editing, canvas ratio adjustments, transitions, and social cuts.",
      accentHex: "#FF2A6D",
    },
    {
      id: "sw-8",
      name: "ChatGPT & AI Studio",
      category: "Design",
      iconName: "Sparkles",
      proficiency: 96,
      glowColor: "emerald",
      description: "Generative AI copywriting, prompt engineering, Google AI Studio, and creative automation.",
      accentHex: "#10A37F",
    },
    {
      id: "sw-9",
      name: "Google Gemini & Claude",
      category: "Design",
      iconName: "Sparkles",
      proficiency: 95,
      glowColor: "purple",
      description: "Advanced AI scripting, research synthesis, content strategy, and creative ideation.",
      accentHex: "#8E24AA",
    },
    {
      id: "sw-10",
      name: "NotebookLM",
      category: "Design",
      iconName: "Sparkles",
      proficiency: 92,
      glowColor: "cyan",
      description: "Grounded AI research, source material synthesis, audio overviews, and structured summaries.",
      accentHex: "#00897B",
    },
  ],

  technicalSkills: [
    {
      id: "tech-1",
      name: "Graphics Design (Photoshop, Illustrator, Canva Pro)",
      category: "Core Design",
      level: "Expert",
      description: "Raster and vector graphic production, brand identity, typography, high-CTR thumbnails, and social media creative assets.",
    },
    {
      id: "tech-2",
      name: "Video Editing (Premiere Pro, After Effects, CapCut, InShot)",
      category: "Core Video",
      level: "Expert",
      description: "High-retention storytelling, kinetic short-form editing for Reels/TikToks, motion graphics, audio mastering, and color grading.",
    },
    {
      id: "tech-3",
      name: "Digital Marketing & Content Strategy",
      category: "Marketing & AI",
      level: "Specialist",
      description: "Social media optimization, organic audience growth tactics, ad creative variants, and conversion-focused visual communication.",
    },
    {
      id: "tech-4",
      name: "AI Tools (ChatGPT, Gemini, Claude, AI Studio, NotebookLM)",
      category: "Marketing & AI",
      level: "Specialist",
      description: "Prompt engineering, AI-assisted video scripting, content research synthesis, and rapid ideation workflow automation.",
    },
    {
      id: "tech-5",
      name: "Effective Communication",
      category: "Workflow",
      level: "Mastery",
      description: "Active listening, transparent feedback loops, clear client consultations, and responsive collaboration across projects.",
    },
    {
      id: "tech-6",
      name: "Time Management",
      category: "Workflow",
      level: "Mastery",
      description: "Disciplined scheduling, consistent deadline fulfillment, rapid turnaround on urgent deliverables, and structured file delivery.",
    },
  ],

  resume: {
    careerObjective: "A dedicated and motivated individual looking for a dynamic opportunity in a growth-oriented organization. Eager to apply my technical and professional skills in graphic design, video editing, and digital media, work collaboratively, and contribute effectively to achieving company goals.",
    education: [
      {
        id: "edu-1",
        degree: "Jalalain",
        status: "Ongoing",
        institution: "Jamia Osmania Madrasah Bangladesh",
        year: "Session: 2026–2027",
        description: "Hasanabad, South Keraniganj, Dhaka",
      },
      {
        id: "edu-2",
        degree: "Sanabia Ul-Ulya",
        status: "Completed",
        institution: "Jamia Osmania Madrasah Bangladesh",
        year: "Session: 2024–2025",
        description: "Hasanabad, South Keraniganj, Dhaka",
      },
      {
        id: "edu-3",
        degree: "Hifzul Quran",
        status: "Certified",
        institution: "Jamia Eshakia Arabia Madrasah",
        year: "Passing Year: 2017",
        description: "Jurain Balur Math, Shyampur, Dhaka-1204",
      },
    ],
    training: [
      {
        id: "train-1",
        title: "Small Business Management (3 Months)",
        institute: "As-Sunnah Skill Development Institute",
        period: "Batch 37 | Session 2026",
        description: "Key Learning Areas & Tools Covered: Graphic Design (Adobe Photoshop, Adobe Illustrator, Canva Pro), Video Editing (Adobe Premiere Pro, Adobe After Effects, CapCut, InShot), Digital Marketing & AI Tools Integration.",
        skillsLearned: [
          "Graphic Design: Adobe Photoshop, Adobe Illustrator, Canva Pro",
          "Video Editing: Adobe Premiere Pro, Adobe After Effects, CapCut, InShot",
          "AI Tools: ChatGPT, Google Gemini, Claude, AI Studio, NotebookLM",
          "Digital Marketing & Small Business Strategy",
          "Effective Communication & Time Management"
        ],
      },
    ],
    coreSkills: [
      "Graphic Design: Adobe Photoshop, Adobe Illustrator, Canva Pro",
      "Video Editing: Adobe Premiere Pro, Adobe After Effects, CapCut, InShot",
      "AI Tools: ChatGPT, Google Gemini, Claude, Google AI Studio, NotebookLM",
      "Soft Skills: Effective Communication, Time Management",
    ],
    reference: {
      name: "Md. Taraqul Islam",
      role: "Instructor / Coordinator",
      organization: "As-Sunnah Skill Development Institute",
      location: "Dhaka, Bangladesh",
    },
  },

  testimonials: [
    {
      id: "test-1",
      clientName: "Shahidul Karim",
      role: "Content Creator & YouTuber",
      companyOrChannel: "Tech Lens BD (120k Subscribers)",
      company: "Tech Lens BD",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      rating: 5,
      feedback: "তোফায়েল ভাইয়ের থাম্বনেইল ডিজাইন ও ভিডিও এডিটিংয়ের কারণে চ্যানেলের ভিউজ এবং সিটিআর অনেক বেড়ে গেছে। সময়মতো পারফেক্ট ডেলিভারি পেয়েছি!",
      quote: "Tofayel transformed my YouTube channel with high-CTR thumbnails and punchy editing. Our audience retention saw an immediate jump!",
      projectType: "YouTube Video Editing & Thumbnails",
    },
    {
      id: "test-2",
      clientName: "Farhan Chowdhury",
      role: "Marketing Director",
      companyOrChannel: "UrbanEdge E-commerce",
      company: "UrbanEdge E-commerce",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      rating: 5,
      feedback: "আমাদের সোশ্যাল মিডিয়া ক্যাম্পেইনের ব্যানার ডিজাইন ও গ্রাফিক্সগুলো এককথায় অসাধারণ হয়েছে। ব্র্যান্ডের থিম ও টাইপোগ্রাফি নিখুঁতভাবে ফুটিয়ে তুলেছেন।",
      quote: "The banner suite and marketing creatives delivered for our brand campaign were top-notch. Clean typography and perfect brand alignment.",
      projectType: "Social Media Banner Suite",
    },
    {
      id: "test-3",
      clientName: "Nusrat Jahan",
      role: "Digital Course Creator",
      companyOrChannel: "Skills Academy Online",
      company: "Skills Academy Online",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
      rating: 5,
      feedback: "অনলাইন কোর্সের ভিডিও এবং অডিও কোয়ালিটি অত্যন্ত প্রফেশনাল ছিল। কাজের গতি ও ওনার চমৎকার যোগাযোগের জন্য আমি ওনার কাজে ভীষণ সন্তুষ্ট।",
      quote: "Exceptional attention to audio clarity and video pacing for my online courses. Seamless communication and super fast turnaround!",
      projectType: "Course Video Production",
    },
  ],

  siteConfig: {
    logoText: "Tofayel A. Shible",
    tagline: "Graphic Designer & Video Editor based in Jurain, Dhaka",
    copyrightText: `© ${new Date().getFullYear()} Tofayel Ahmad Shible. All rights reserved.`,
    primaryCtaText: "View My Work",
    secondaryCtaText: "Contact Me",
  },
};
